#include <iostream>
using namespace std;
main(){
int num1,num2,num3,num4,num5,num6,num7,num8,num9,num10,num11,num12,num13,num14,num15,sum5num,mul5num,sub5num,output;
cout<<"enter num1";
cin>>num1;
cout<<"enter num2";
cin>>num2;
cout<<"enter num3";
cin>>num3;
cout<<"enter num4";
cin>>num4;
cout<<"enter num5";
cin>>num5;
cout<<"enter num6";
cin>>num6;
cout<<"enter num7";
cin>>num7;
cout<<"enter num8";
cin>>num8;
cout<<"enter num9";
cin>>num9;
cout<<"enter num10";
cin>>num10;
cout<<"enter num11";
cin>>num11;
cout<<"enter num12";
cin>>num12;
cout<<"enter num13";
cin>>num13;
cout<<"enter num14";
cin>>num14;
cout<<"enter num15";
cin>>num15;
sum5num=num1+num2+num3+num4+num5;
cout<<"sum of first 5 numbers:"<<sum5num;
cout<<""<<endl;
mul5num=num6*num7*num8*num9*num10;
cout<<"multiplication of next5 num:"<<mul5num;
cout<<""<<endl;
sub5num=num11-num12-num13-num14-num15;
cout<<"subtraction of next 5 num"<<sub5num;
cout<<""<<endl;
output=(sum5num+mul5num)-sub5num;
cout<<"final result"<<output;
}
